knp_paginator:
    page_range: 5        # Quantidade de páginas exibidas no paginador
    default_options:
        page_name: page  # Nome do parâmetro na URL
        sort_field_name: sort
        sort_direction_name: direction        
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Template padrão de paginação
